In [2]:
import numpy as np

In [3]:
x = np.arange(-10, 10, 1) # -10~9를 x에 대입
print(type(x))
print(x)

<class 'numpy.ndarray'>
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


In [4]:
y = 2*x - 1
print(y)

[-21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5   7   9  11  13
  15  17]


In [5]:
# 그래프 그리기
import matplotlib.pyplot as plt
plt.rcParams.update({
    'text.color': "white",
    'axes.labelcolor': "white",

    'xtick.color': "white",
    'ytick.color': "white"
})

plt.plot(x, y)
plt.show()

<Figure size 640x480 with 1 Axes>

In [6]:
print("x 배열의 원소 개수: ", x.shape[0]) # x.shape[0] == len(x)
idx = np.arange(x.shape[0])  # np.arange(20) => 0~19 idx 대입
print("기존 인덱스: ", idx)
np.random.shuffle(idx)
print("섞인 인덱스: ", idx)

x 배열의 원소 개수:  20
기존 인덱스:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
섞인 인덱스:  [10  9 11  2  0 14  8 19  7  6 16 15 17  1  4 13 18  5  3 12]


In [7]:
x = x[idx]
print("x: ", x)
y = y[idx]
print("y: ", y)

x:  [  0  -1   1  -8 -10   4  -2   9  -3  -4   6   5   7  -9  -6   3   8  -5
  -7   2]
y:  [ -1  -3   1 -17 -21   7  -5  17  -7  -9  11   9  13 -19 -13   5  15 -11
 -15   3]


In [8]:
x_new = x.reshape(-1, 1)
print(x_new)

[[  0]
 [ -1]
 [  1]
 [ -8]
 [-10]
 [  4]
 [ -2]
 [  9]
 [ -3]
 [ -4]
 [  6]
 [  5]
 [  7]
 [ -9]
 [ -6]
 [  3]
 [  8]
 [ -5]
 [ -7]
 [  2]]


In [9]:
# LinearRegression 클래스 함수는 통계학의 선형회귀분석을 처리.
from sklearn.linear_model import LinearRegression

In [10]:
lr = LinearRegression()
lr.fit(x_new, y)    # 넣으므로써 lr에 식이 생김 y = 2*x-1
# 이때 x_new는 2차원 배열, y는 1차원 배열이다.
print("기울기: ", lr.coef_)
print("y절편: ", lr.intercept_)

기울기:  [2.]
y절편:  -1.0000000000000004


In [11]:
x_test = np.arange(11, 16, 1).reshape(-1 , 1)
x_test

array([[11],
       [12],
       [13],
       [14],
       [15]])

In [12]:
y_hat = lr.predict(x_test)  # 식을 응용 y=2*x-1
y_hat

array([21., 23., 25., 27., 29.])

In [13]:
#
from tensorflow import keras
from tensorflow.keras.layers import Dense

c:\Users\lunaw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\Users\lunaw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\Users\lunaw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\Users\lunaw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passi

In [14]:
# Sequential 클래스 함수를 사용해서 신경만 객체를 생성
dnn = keras.Sequential()

In [15]:
# units=1  즉 출력 데이터가 1가지 종류
# input_shape=(1,) 입력 데이터의 데이터 구조 지정
# 입력 변수 x가 1개라는 뜻...
dnn.add(Dense(units=1, input_shape=(1,)))

Instructions for updating:
Colocations handled automatically by placer.


In [16]:
# optimizer: 오차를 줄이는데 사용하는 최적화 알고리즘
# loss: 예측값의 오차를 측정하는 기준
dnn.compile(optimizer='sgd', loss='mse')

Instructions for updating:
Use tf.cast instead.


In [17]:
# summary: 인공신경망 구조 출력
dnn.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [18]:
# epochs=n n번 반복 학습
# y = 2*x-1
dnn.fit(x_new, y, epochs=1000)

Instructions for updating:
Use tf.cast instead.
Epoch 1/1000
20/20 [==============================] - 0s 9ms/sample - loss: 156.7575
Epoch 2/1000
20/20 [==============================] - 0s 50us/sample - loss: 17.8454
Epoch 3/1000
20/20 [==============================] - 0s 50us/sample - loss: 2.7009
Epoch 4/1000
20/20 [==============================] - 0s 50us/sample - loss: 1.0233
Epoch 5/1000
20/20 [==============================] - 0s 50us/sample - loss: 0.8122
Epoch 6/1000
20/20 [==============================] - 0s 100us/sample - loss: 0.7616
Epoch 7/1000
20/20 [==============================] - 0s 50us/sample - loss: 0.7297
Epoch 8/1000
20/20 [==============================] - 0s 100us/sample - loss: 0.7008
Epoch 9/1000
20/20 [==============================] - 0s 50us/sample - loss: 0.6732
Epoch 10/1000
20/20 [==============================] - 0s 50us/sample - loss: 0.6468
Epoch 11/1000
20/20 [==============================] - 0s 100us/sample - loss: 0.6214
Epoch 12/1000
20/20 [

In [20]:
y_hat_dnn = dnn.predict(x_test)
y_hat_dnn

array([[21.000002],
       [23.000002],
       [25.000002],
       [27.000002],
       [29.000002]], dtype=float32)

In [1]:
from keras import optimizers

In [ ]:
optimizers.SGD