# Pandas - Series

In [1]:
import numpy as np
import pandas as pd

### 1. 시리즈 생성
- Numpy 1차원 배열 + 인덱스

In [3]:

pop = [9904312, 3448737, 2890451, 2466052]          # 서울, 부산, 인천, 대구
pop[0], pop[2]

(9904312, 2890451)

In [4]:
metro = pd.Series(pop, index=['서울', '부산', '인천', '대구'])
metro

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [7]:
# 값 하나를 인덱싱할 경우
metro['서울'], metro[0]

(9904312, 9904312)

In [11]:
# 여러값을 가져올 경우 - 시리즈 형식
metro[[0,1]]

서울    9904312
부산    3448737
dtype: int64

In [12]:
metro[['서울', '부산']]
# metro['서울', '부산']는 Error 

서울    9904312
부산    3448737
dtype: int64

In [10]:
# metro 데이터 타입
metro.values, type(metro.values)

(array([9904312, 3448737, 2890451, 2466052], dtype=int64), numpy.ndarray)

In [15]:
dice = pd.Series(np.random.randint(1, 7, 10))
pd.DataFrame(dice, columns=['주사위'])

주사위
0    5
1    5
2    3
3    1
4    6
5    5
6    6
7    3
8    2
9    2

In [16]:
# 시리즈 데이터는 넘파이 어레이이므로 수식을 바로 적용할 수 있음
metro / 1000000

서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
dtype: float64

In [17]:
dice * 10

0    50
1    50
2    30
3    10
4    60
5    50
6    60
7    30
8    20
9    20
dtype: int32

In [18]:
pd.DataFrame(metro, columns=['인구수'])

인구수
서울  9904312
부산  3448737
인천  2890451
대구  2466052

### 2. 시리즈와 딕셔너리

In [67]:
# 딕셔너리의 키가 시리즈의 인덱스가 됨
city = {'서울':9631482,'부산':3393191,'인천':2890451,'대전':1490158}
metro2 = pd.Series(city)
metro2          # 딕셔너리를 시리즈로 만들면 인덱스를 따로 지정하지 않아도 됨

서울    9631482
부산    3393191
인천    2890451
대전    1490158
dtype: int64

In [68]:
for key, value in metro2.items():
    print(key, value)

서울 9631482
부산 3393191
인천 2890451
대전 1490158


In [69]:
metro - metro2

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천         0.0
dtype: float64

In [70]:
# inf 무한대(Infinity), nan 결측치(NaN = Null) --> 실수
a = np.array([np.inf, np.nan, 0, 1, 2])
a

array([inf, nan,  0.,  1.,  2.])

### 3. 속성

In [71]:
metro.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [72]:
metro.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [73]:
metro

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 광역시, dtype: int64

In [74]:
metro.name = '광역시'
metro

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 광역시, dtype: int64

### 4. Method

- count, unique, nunique,value_counts

In [75]:
dice

0    5
1    5
2    3
3    1
4    6
5    5
6    6
7    3
8    2
9    2
dtype: int32

In [76]:
# element의 갯수
dice.count()            # dice = pd.Series(np.random.randint(1, 7, 10))

10

In [77]:
# 고유한 값 = 전체 집합
dice.unique()

array([5, 3, 1, 6, 2], dtype=int64)

In [78]:
# 고유한 값별로 갯수
dice.value_counts()

5    3
6    2
3    2
2    2
1    1
dtype: int64

- sum, min, max, mean

In [79]:
dice.sum(), dice.min(), dice.max(), dice.mean()

(38, 1, 6, 3.8)

In [80]:
metro.mean()

4677388.0

In [81]:
# 요약 통계
metro.describe()

count    4.000000e+00
mean     4.677388e+06
std      3.507776e+06
min      2.466052e+06
25%      2.784351e+06
50%      3.169594e+06
75%      5.062631e+06
max      9.904312e+06
Name: 광역시, dtype: float64

- Sorting: sort_values, sort_index

In [82]:
# 데이터를 기준으로 오름차순
metro.sort_values()

대구    2466052
인천    2890451
부산    3448737
서울    9904312
Name: 광역시, dtype: int64

In [83]:
# 데이터를 기준으로 내림차순
metro.sort_values(ascending=False)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 광역시, dtype: int64

In [84]:

metro.sort_values()[::-1]

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 광역시, dtype: int64

In [85]:
metro.sort_index()          # index를 기준으로 정렬 '가나다'순

대구    2466052
부산    3448737
서울    9904312
인천    2890451
Name: 광역시, dtype: int64

- 결측치(Na, NaN, Null)처리 - isna(), dropna(), fillna()

In [86]:
dm = metro - metro2
dm

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천         0.0
dtype: float64

In [87]:
dm.isna()           # 값이 없으면(즉 Null이면) True를 출력, 값이 존재하면 False 

대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool

In [88]:
dm.isnull()         # = dm.isna()

대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool

In [89]:
# 0 이 아닌 값이 나오면 결측치가 있음
dm.isna().sum()     # 결측치가 몇개인 확인 True = 1로 False = 0이기 때문에 가능

2

In [90]:
# metro 에는 결측치가 없음
metro.isnull().sum()

0

In [91]:
# 결측치 해결: 1.제거 2.대체(수치형 데이터: 평균, 중앙값; 카테고리형: 최빈값)

# 결측치를 평균으로 대체
dm.fillna(dm.mean())

대구    109458.666667
대전    109458.666667
부산     55546.000000
서울    272830.000000
인천         0.000000
dtype: float64

In [92]:
# 결측치를 중앙값으로 대체
dm.fillna(dm.median())

대구     55546.0
대전     55546.0
부산     55546.0
서울    272830.0
인천         0.0
dtype: float64

In [93]:
# 결측치를 0으로 대체하고 정수형으로 변경
dm.fillna(0).astype(int)

대구         0
대전         0
부산     55546
서울    272830
인천         0
dtype: int32

In [94]:
# 결측치 제거
dm.dropna()

부산     55546.0
서울    272830.0
인천         0.0
dtype: float64

- inplace option

In [95]:
dm2 = dm.dropna()
dm2

부산     55546.0
서울    272830.0
인천         0.0
dtype: float64

In [97]:
dm.dropna(inplace=True)
dm

부산     55546.0
서울    272830.0
인천         0.0
dtype: float64

In [98]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  ...    deck  embark_town  alive  alone
0         0       3    male  22.0  ...     NaN  Southampton     no  False
1         1       1  female  38.0  ...       C    Cherbourg    yes  False
2         1       3  female  26.0  ...     NaN  Southampton    yes   True
3         1       1  female  35.0  ...       C  Southampton    yes  False
4         0       3    male  35.0  ...     NaN  Southampton     no   True

[5 rows x 15 columns]

In [101]:
age = titanic['age']
age.isna().sum(), age.count()

(177, 714)